name: otaku_stream
description: OtakuStream — multi-source novel, manga and anime reader.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  logger: ^2.5.0
  google_nav_bar: ^5.0.7
  adaptive_theme: ^3.6.0
  responsive_framework: ^1.5.1
  nb_utils: ^7.1.4
  icons_launcher: ^3.0.0
  mix: ^1.5.2
  cloudflare_bypass: ^0.0.1
  cloudflare_interceptor: ^0.0.3
  dart_web_scraper: ^0.1.0
  flutter_cors_image: ^0.3.13
  photo_view: ^0.15.0
  chewie: ^1.14.1
  video_player: ^2.11.1
  dns_client: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
